create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('user','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.question_difficulty as enum ('easy','medium','hard'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,full_name text,avatar_url text,role public.user_role not null default 'user',preferred_language text not null default 'en',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(),name_en text not null unique,name_as text,description text,created_at timestamptz not null default now());
create table if not exists public.notes (id uuid primary key default gen_random_uuid(),title_en text not null,title_as text,excerpt_en text,excerpt_as text,content_en text not null,content_as text,category_id uuid references public.categories(id) on delete set null,slug text not null unique,published boolean not null default false,pdf_path text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.questions (id uuid primary key default gen_random_uuid(),question_en text not null,question_as text,options jsonb not null,correct_index smallint not null check(correct_index between 0 and 3),explanation_en text,explanation_as text,difficulty public.question_difficulty not null default 'medium',category_id uuid references public.categories(id) on delete set null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint options_is_array check(jsonb_typeof(options)='array' and jsonb_array_length(options)=4));
create table if not exists public.tests (id uuid primary key default gen_random_uuid(),title_en text not null,title_as text,description_en text,description_as text,duration_minutes integer not null check(duration_minutes between 1 and 600),published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.test_questions (test_id uuid not null references public.tests(id) on delete cascade,question_id uuid not null references public.questions(id) on delete cascade,position integer not null check(position>=0),primary key(test_id,question_id),unique(test_id,position));
create table if not exists public.attempts (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,test_id uuid not null references public.tests(id) on delete cascade,answers jsonb not null default '{}'::jsonb,score integer not null default 0,total integer not null check(total>=0),started_at timestamptz not null default now(),submitted_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.bookmarks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,note_id uuid not null references public.notes(id) on delete cascade,created_at timestamptz not null default now(),unique(user_id,note_id));
create table if not exists public.current_affairs (id uuid primary key default gen_random_uuid(),title text not null,summary text not null,category text,date date not null,source text,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists notes_category_idx on public.notes(category_id);create index if not exists notes_published_idx on public.notes(published,created_at desc);create index if not exists questions_category_idx on public.questions(category_id);create index if not exists tests_published_idx on public.tests(published,created_at desc);create index if not exists attempts_user_idx on public.attempts(user_id,submitted_at desc);create index if not exists current_affairs_published_idx on public.current_affairs(published,date desc);

alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.notes enable row level security;alter table public.questions enable row level security;alter table public.tests enable row level security;alter table public.test_questions enable row level security;alter table public.attempts enable row level security;alter table public.bookmarks enable row level security;alter table public.current_affairs enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;revoke all on function public.is_admin() from public;grant execute on function public.is_admin() to authenticated;

create policy profiles_select_own on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());create policy profiles_update_own on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());create policy profiles_admin_all on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy categories_public_read on public.categories for select to anon,authenticated using(true);create policy categories_admin_write on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy notes_public_read on public.notes for select to anon,authenticated using(published=true or public.is_admin());create policy notes_admin_write on public.notes for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy questions_admin_all on public.questions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy tests_public_read on public.tests for select to anon,authenticated using(published=true or public.is_admin());create policy tests_admin_write on public.tests for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy test_questions_admin_all on public.test_questions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy attempts_own_read on public.attempts for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy attempts_own_insert on public.attempts for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.tests t where t.id=test_id and t.published=true));create policy attempts_own_update on public.attempts for update to authenticated using(user_id=auth.uid() and submitted_at is null) with check(user_id=auth.uid() and submitted_at is null);
create policy bookmarks_own_all on public.bookmarks for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy current_affairs_public_read on public.current_affairs for select to anon,authenticated using(published=true or public.is_admin());create policy current_affairs_admin_write on public.current_affairs for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public) values('notes-pdfs','notes-pdfs',false) on conflict(id) do nothing;
create policy notes_pdf_admin_insert on storage.objects for insert to authenticated with check(bucket_id='notes-pdfs' and public.is_admin());create policy notes_pdf_admin_update on storage.objects for update to authenticated using(bucket_id='notes-pdfs' and public.is_admin()) with check(bucket_id='notes-pdfs' and public.is_admin());create policy notes_pdf_admin_delete on storage.objects for delete to authenticated using(bucket_id='notes-pdfs' and public.is_admin());create policy notes_pdf_auth_read on storage.objects for select to authenticated using(bucket_id='notes-pdfs' and (public.is_admin() or exists(select 1 from public.notes n where n.pdf_path=name and n.published=true)));
